# Generated by Django 4.0.4 on 2022-04-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebpage', '0002_testtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customerid', models.CharField(blank=True, db_column='CustomerID', max_length=100, null=True)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=100, null=True)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('postalcode', models.IntegerField(blank=True, db_column='PostalCode', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
    ]
